stages:
- stage: build
  displayName: 'Build and test'
  jobs:
  - job: build_ubuntu_latest
    displayName: 'Ubuntu build'
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - checkout: self

    - script: python3 -m pip install --upgrade pip setuptools wheel
      displayName: 'Install pip'

    - script: python3 -m pip install -r requirements.txt
      displayName: 'Install requirements'

    - script: python3 setup.py build
      displayName: 'Build'

    - script: |
        ln -s build/lib*/cutil.cpython*.so .
        python3 -m unittest tests/test_volumes.py
        python3 -m unittest tests/test_script.py
      displayName: 'Test'

