stages:
- stage: build
  displayName: 'Build and test'
  jobs:
  - job: build_ubuntu_latest
    displayName: 'Ubuntu build'
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - checkout: self

    - script: |
        python -m pip install --upgrade pip
        pip install build
      displayName: 'Install build system'

    - script: python -m build
      displayName: 'Build'

    - script: |
        pip install dist/*.whl
      displayName: 'Install'

    - script: |
        pip install -r test-requirements.txt
        pytest -v
      displayName: 'Test'
